config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :users, :locations

    #home page routes
  get "/landing", to: "welcome#landing"

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def index
		@locations = Location.all.order("created_at DESC")
	end

	def new
		@location = Location.new
	end

	def show
		@location = Location.find(params[:id])
	end

	def create
		location_params = params.require(:location).permit(:name, :address, :img_url)
		@location = Location.new(location_params)
		@location.save
		redirect_to @location
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def landing
  	render :home
  end

  def users
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

     <link href="https://fonts.googleapis.com/css?family=Open+Sans|Lato" rel="stylesheet">
</head>

<body>

  <nav class="navbar navbar-default example2">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/"><img src="logo.png" width="200px"></a>
        
      </div>
      <div id="navbar2" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="/">HOME</a></li>
          <li><a href="/locations">FEED</a></li>
          <li><a href="/users">LEADERBOARD</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">WELCOME, STEPH!<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>

  </nav>
<%= yield %>

     <div class="col-xs-3 text-center">
        <%= fa_icon "line-chart", class:"fa-4x" %><br>
        <%= link_to "TRENDING", locations_path, class: "btn" %>
      </div>

       <div class="col-xs-3 text-center">
        <%= fa_icon "map-marker", class:"fa-4x" %><br>
        <%= link_to "FEED", locations_path, class: "btn" %>
      </div>

      <div class="col-xs-3 text-center">
          <%= fa_icon "camera-retro 2x", class:"fa-4x"%><br>
        <%= link_to "POST", new_location_path, class: "btn" %>
      </div>

      <div class="col-xs-3 text-center">
        <%= fa_icon "user", class:"fa-4x" %><br>
        <%= link_to "PROFILE", '/users/1', class: "btn" %>
      </div>


</div>
</body>
</html>

app/views/locations/index.html.erb
<div class="container-fluid text-center">
	<h1>Location Feed</h1>
		<iframe src="https://www.google.com/maps/d/embed?mid=1xzgcBs9jwqW1rxeZOV2x_afYIso" width="640" height="480"></iframe>

	<% @locations.each do |location| %>
		<div class="row">
			<div class="col-md-12 location">
				<div class="col-md-4">
				<img src="<%= location.img_url %>" width="300px" height="300px">
				</div>
				<div class="col-md-8">
					<h2><%= location.name %></h2>
					<h4>
						Location: <%= location.address %>
					</h4>
					<h4>
						Tags: <%= location.tags %>
					</h4>
					<div class="btn btn-primary">
						 <%= link_to "VIEW", location_path(location), style:"color:white"%>
					</div>
					<h4><a href="<%= location.map_url %>">VIEW IN GOOGLE MAPS</a></h4>
				</div>
				<% end %>
			</div>
		</div>
	</div>

app/views/locations/new.html.erb
<div class="container-fluid text-center">
<%= form_for :location, url: locations_path do |f| %>

  <h3>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </h3>

  <h3>
    <%= f.label :location %><br>
    <%= f.text_area :address %>
  </h3>

  <h3>
    <%= f.label :tags%><br>
    <%= f.text_field :tags%>
  </h3>

  <h3>
    <%= f.label :img_URL %><br>
    <%= f.text_area :img_url %>
  </h3>
 
  <h3>
    <%= f.submit %>
  </h3>
<% end %>
<div class="photo"> 
 <video autoplay="true" id="videoElement">
    </video>
</div>
<script>
 var video = document.querySelector("#videoElement");
 
navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia || navigator.oGetUserMedia;
 
if (navigator.getUserMedia) {       
    navigator.getUserMedia({video: true}, handleVideo, videoError);
}
 
function handleVideo(stream) {
    video.src = window.URL.createObjectURL(stream);
}
 
function videoError(e) {
    // do something
}
</script>
 </div>

app/views/locations/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-9">
			<div class="workshop-box center-block">

				<h2><%= @location.name %></h2>
				<h4>
					<span class="h4-big">Location:<%= @location.address %></span><br class="br-big">
				</h4>
				<h4>
					<span class="h4-big">Tags:<%= @location.tags %></span><br class="br-big">
				</h4>

			<%= image_tag @location.img_url, class: "img-responsive workshop-img" %>
				</div>
			</div>
			</div>

app/views/users/index.html.erb
<div class="container">
<div class="form-group center-align" style="background-color: white">


<div style="font-size:42px">
    <h1 style="text-align:center">LEADERBOARD</h1>
    <ol>
      <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzcgRmN8v99GbAMuESP16dA2ejqHneW8VYslb4QA9bNQJEUyfKtg">Khushi 300</li>
      <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzcgRmN8v99GbAMuESP16dA2ejqHneW8VYslb4QA9bNQJEUyfKtg">Steph 299</li>
      <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzcgRmN8v99GbAMuESP16dA2ejqHneW8VYslb4QA9bNQJEUyfKtg">Zarah 236</li>
      <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzcgRmN8v99GbAMuESP16dA2ejqHneW8VYslb4QA9bNQJEUyfKtg">Maha 198</li>
      <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzcgRmN8v99GbAMuESP16dA2ejqHneW8VYslb4QA9bNQJEUyfKtg">Jennessa 176</li>
      <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzcgRmN8v99GbAMuESP16dA2ejqHneW8VYslb4QA9bNQJEUyfKtg">Sunny 147</li>
      <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzcgRmN8v99GbAMuESP16dA2ejqHneW8VYslb4QA9bNQJEUyfKtg">Muying 123</li>
</ol>
  </div>
</div>
</div>
</div>

app/views/users/new.html.erb
new.index.html 

app/views/users/show.html.erb
		<div class="container-fluid ">

	<div class="text-center">
		<h1>Welcome, Steph!</h1><h2>Here's where you've explored:</h2>
		<h4>Location: San Francisco</h4><br>
		</div>

		<%= link_to image_tag("instagramFeed.jpg", class:"img-responsive") %>
		<img class="img-responsive" src="/images/instagramFeed.jpg" alt="Instagram Feed">

	<iframe src="https://www.google.com/maps/d/embed?mid=1xzgcBs9jwqW1rxeZOV2x_afYIso" width="640" height="480" class="center-block"></iframe>


</div>

app/views/welcome/home.html.erb
<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

	</head>


			<img src="newtheater.png" width="100%">

app/views/welcome/index.html.erb
<div style="background-image:url(http://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2015/08/SANFRANCISCO.jpg); width:1692px; height:871px;">

  <div class="row">
    <div class="col-lg-4 col-lg-offset-4 col-xs-12" style="text-align:center">

      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
<div id="heading">
  <h1>Discover Your City</h1>
</div>
  <form action="/log_in" method="POST">

    <div class="form-group">
        <label>
            Email
            <input type="email" name="email" class="form-control">
        </label>
    </div>
   <br>

    <div class="form-group">
      <label>
          Password
          <input type="password" name="password" class="form-control">
      </label>
    </div>
    <br>


    <div class="btn btn-primary">
    	<%= link_to "LOG IN", landing_path, class:"button" %>
    </div>
</form> 